- name: Deployment of Genre Classification application
  hosts: all
  become: yes
  vars:
    remote_dir: "/home/ubuntu/genre_clf"
    local_files:
      - "genre_clf/server/requirements.txt"
      - "genre_clf/server/app.py"
      - "genre_clf/server/utils/feature_extraction.py"
      - "genre_clf/server/model/min_max_scaler.pkl"
      - "genre_clf/server/model/xgb_mgen.pkl"
      - "genre_clf/server/templates/index.html"
      - "genre_clf/server/templates/result.html"
       
  tasks:
    - name: Ensure the target directory exists
      ansible.builtin.file:
        path: "{{ remote_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy files to remote server
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ remote_dir }}/"
      loop: "{{ local_files }}"

    - name: Install all requirements
      ansible.builtin.command:
        cmd: pip install -r requirements.txt
        chdir: "{{ remote_dir }}/server"  # Переключаемся на директорию

    - name: Start python file
      ansible.builtin.command:
        cmd: python3 app.py
        chdir: "{{ remote_dir }}/server"  # Переключаемся на директорию
