- name: Deployment of Genre Classification application
  hosts: all
  become: yes
  vars:
    remote_dir: "/home/ubuntu/genre_clf"
    local_files:
       - "genre_clf/server/requirements.txt"
       - "genre_clf/server/app.py"
       - "genre_clf/server/utils/feature_extraction.py"
       - "genre_clf/server/model/min_max_scaler.pkl"
       - "genre_clf/server/model/xgb_mgen.pkl"
       - "genre_clf/server/templates/index.html"
       - "genre_clf/server/templates/result.html"
  tasks:

    - name: Ensure the target directory exists
      ansible.builtin.file:
        path: "{{ remote_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy files to remote server
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ remote_dir }}/"
      loop: "{{ local_files }}"
    
    - name: Go to the directory genre_clf/server
      ansible.builtin.shell: 
        _raw_params: "cd {{ remote_dir }}/server"
        chdir: "{{ remote_dir }}/server"  # Это сменит директорию перед выполнением команды
  
    - name: Install all requirements
      ansible.builtin.shell:
        _raw_params: "pip install -r requirements.txt"
        chdir: "{{ remote_dir }}/server"  # Убедитесь, что вы находитесь в правильной директории

    - name: Start python file
      ansible.builtin.shell:
        _raw_params: "python3 app.py"
        chdir: "{{ remote_dir }}/server"  # Убедитесь, что вы находитесь в правильной директории
